POST http://localhost:5001/user HTTP/1.1
Content-Type: application/json

{
    "user": {
        "username": "test1",
        "score": 500
    }
}

#####

GET http://localhost:5001/leaderboard HTTP/1.1
Content-Type: application/json
